/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.EntregaDAO;
import DTO.EntregaDTO;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author LABINFO
 */
public class frmentrega extends javax.swing.JFrame {

    private static final DateTimeFormatter FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    /**
     * Creates new form frmentrega
     */
    public frmentrega() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        lblNr = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        lblDataSaida = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblPedido = new javax.swing.JLabel();
        lblEntregador = new javax.swing.JLabel();
        txtnr = new javax.swing.JTextField();
        txtvalor = new javax.swing.JTextField();
        txtdatasaida = new javax.swing.JTextField();
        cbstatus = new javax.swing.JComboBox<>();
        txtpedido = new javax.swing.JTextField();
        txtentregador = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Entrega");

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitulo.setText("Entrega");

        lblNr.setText("Nr (Automático)");

        lblValor.setText("Valor Entrega");

        lblDataSaida.setText("Data Saída");

        lblStatus.setText("Status");

        lblPedido.setText("Nr Pedido");

        lblEntregador.setText("Código Entregador");

        txtnr.setEditable(false);

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendente", "Em rota", "Entregue", "Cancelada" }));

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNr)
                            .addComponent(lblValor)
                            .addComponent(lblDataSaida)
                            .addComponent(lblStatus)
                            .addComponent(lblPedido)
                            .addComponent(lblEntregador))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnr, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdatasaida, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtentregador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOK)
                        .addGap(10, 10, 10)
                        .addComponent(btnPesquisar)
                        .addGap(10, 10, 10)
                        .addComponent(btnAlterar)
                        .addGap(10, 10, 10)
                        .addComponent(btnExcluir)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitulo)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNr)
                    .addComponent(txtnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataSaida)
                    .addComponent(txtdatasaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPedido)
                    .addComponent(txtpedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEntregador)
                    .addComponent(txtentregador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnPesquisar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private EntregaDTO montarEntregaDTO() {
        EntregaDTO objEntregaDTO = new EntregaDTO();
        if (!txtnr.getText().isEmpty()) {
            objEntregaDTO.setNr(Integer.parseInt(txtnr.getText()));
        }
        try {
            objEntregaDTO.setValorEntrega(new BigDecimal(txtvalor.getText().replace(",", ".")));
        } catch (NumberFormatException e) {
            objEntregaDTO.setValorEntrega(BigDecimal.ZERO);
        }
        objEntregaDTO.setDataSaida(lerDataSaida());
        objEntregaDTO.setStatus(cbstatus.getSelectedItem().toString());
        try {
            objEntregaDTO.setNrPedido(Integer.parseInt(txtpedido.getText()));
        } catch (NumberFormatException e) {
            objEntregaDTO.setNrPedido(0);
        }
        try {
            objEntregaDTO.setCodigoEntregador(Integer.parseInt(txtentregador.getText()));
        } catch (NumberFormatException e) {
            objEntregaDTO.setCodigoEntregador(0);
        }
        return objEntregaDTO;
    }

    private LocalDateTime lerDataSaida() {
        String texto = txtdatasaida.getText().trim().replace("T", " ");
        if (texto.isEmpty()) {
            return null;
        }
        try {
            return LocalDateTime.parse(texto, FMT);
        } catch (Exception e) {
            return null;
        }
    }

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        EntregaDAO objEntregaDAO = new EntregaDAO();
        objEntregaDAO.cadastrarEntrega(montarEntregaDTO());
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        frmpesquisarentrega objFrmpesquisarentrega = new frmpesquisarentrega();
        objFrmpesquisarentrega.setVisible(true);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (txtnr.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pesquise uma entrega antes de alterar!");
            return;
        }
        EntregaDAO objEntregaDAO = new EntregaDAO();
        objEntregaDAO.alterarEntrega(montarEntregaDTO());
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (txtnr.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pesquise uma entrega antes de excluir!");
            return;
        }
        EntregaDAO objEntregaDAO = new EntregaDAO();
        objEntregaDAO.excluirEntrega(montarEntregaDTO());
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmentrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmentrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmentrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmentrega.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmentrega().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPesquisar;
    public static javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel lblDataSaida;
    private javax.swing.JLabel lblEntregador;
    private javax.swing.JLabel lblNr;
    private javax.swing.JLabel lblPedido;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblValor;
    public static javax.swing.JTextField txtdatasaida;
    public static javax.swing.JTextField txtentregador;
    public static javax.swing.JTextField txtnr;
    public static javax.swing.JTextField txtpedido;
    public static javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
