/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.PedidoDAO;
import DTO.ItemPedidoDTO;
import DTO.PedidoDTO;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author LABINFO
 */
public class frmpedido extends javax.swing.JFrame {

    private static final DateTimeFormatter FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    /**
     * Creates new form frmpedido
     */
    public frmpedido() {
        initComponents();
        txtdatahora.setText(LocalDateTime.now().format(FMT));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        lblNr = new javax.swing.JLabel();
        lblDataHora = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblFuncionario = new javax.swing.JLabel();
        txtnr = new javax.swing.JTextField();
        txtdatahora = new javax.swing.JTextField();
        cbstatus = new javax.swing.JComboBox<>();
        txttotal = new javax.swing.JTextField();
        txtcliente = new javax.swing.JTextField();
        txtfuncionario = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pedido");

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitulo.setText("Pedido");

        lblNr.setText("Nr (Automático)");

        lblDataHora.setText("Data e Hora");

        lblStatus.setText("Status");

        lblTotal.setText("Total");

        lblCliente.setText("Código Cliente");

        lblFuncionario.setText("Código Funcionário");

        txtnr.setEditable(false);

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendente", "Em preparo", "A caminho", "Entregue", "Cancelado" }));

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNr)
                            .addComponent(lblDataHora)
                            .addComponent(lblStatus)
                            .addComponent(lblTotal)
                            .addComponent(lblCliente)
                            .addComponent(lblFuncionario))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnr, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdatahora, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOK)
                        .addGap(10, 10, 10)
                        .addComponent(btnPesquisar)
                        .addGap(10, 10, 10)
                        .addComponent(btnAlterar)
                        .addGap(10, 10, 10)
                        .addComponent(btnExcluir)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitulo)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNr)
                    .addComponent(txtnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataHora)
                    .addComponent(txtdatahora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(txtcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncionario)
                    .addComponent(txtfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOK)
                    .addComponent(btnPesquisar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private PedidoDTO montarPedidoDTO() {
        PedidoDTO objPedidoDTO = new PedidoDTO();
        if (!txtnr.getText().isEmpty()) {
            objPedidoDTO.setNr(Integer.parseInt(txtnr.getText()));
        }
        objPedidoDTO.setDataHora(lerDataHora());
        objPedidoDTO.setStatus(cbstatus.getSelectedItem().toString());
        try {
            objPedidoDTO.setTotal(new BigDecimal(txttotal.getText().replace(",", ".")));
        } catch (NumberFormatException e) {
            objPedidoDTO.setTotal(BigDecimal.ZERO);
        }
        try {
            objPedidoDTO.setCodigoCliente(Integer.parseInt(txtcliente.getText()));
        } catch (NumberFormatException e) {
            objPedidoDTO.setCodigoCliente(0);
        }
        try {
            objPedidoDTO.setCodigoFuncionario(Integer.parseInt(txtfuncionario.getText()));
        } catch (NumberFormatException e) {
            objPedidoDTO.setCodigoFuncionario(0);
        }
        return objPedidoDTO;
    }

    private LocalDateTime lerDataHora() {
        String texto = txtdatahora.getText().trim().replace("T", " ");
        try {
            return LocalDateTime.parse(texto, FMT);
        } catch (Exception e) {
            return LocalDateTime.now();
        }
    }

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        PedidoDAO objPedidoDAO = new PedidoDAO();
        objPedidoDAO.cadastrarPedido(montarPedidoDTO(), new ArrayList<ItemPedidoDTO>());
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        frmpesquisarpedido objFrmpesquisarpedido = new frmpesquisarpedido();
        objFrmpesquisarpedido.setVisible(true);
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (txtnr.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pesquise um pedido antes de alterar!");
            return;
        }
        PedidoDAO objPedidoDAO = new PedidoDAO();
        objPedidoDAO.alterarPedido(montarPedidoDTO());
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (txtnr.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pesquise um pedido antes de excluir!");
            return;
        }
        PedidoDAO objPedidoDAO = new PedidoDAO();
        objPedidoDAO.excluirPedido(montarPedidoDTO());
    }//GEN-LAST:event_btnExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmpedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmpedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmpedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmpedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmpedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPesquisar;
    public static javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDataHora;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblNr;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTotal;
    public static javax.swing.JTextField txtcliente;
    public static javax.swing.JTextField txtdatahora;
    public static javax.swing.JTextField txtfuncionario;
    public static javax.swing.JTextField txtnr;
    public static javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
