/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import java.awt.Color;

/**
 *
 * @author LABINFO
 */
public class telaprincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaprincipal
     */
    public telaprincipal() {
        initComponents();
        setSize(440, 400);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnfuncionario = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btncliente = new javax.swing.JButton();
        btncategoria = new javax.swing.JButton();
        btnpedido = new javax.swing.JButton();
        btnitempedido = new javax.swing.JButton();
        btnentregador = new javax.swing.JButton();
        btnentrega = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btncliente.setText("CLIENTE");
        btncliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclienteActionPerformed(evt);
            }
        });
        btncliente.setBounds(35, 75, 160, 45);
        getContentPane().add(btncliente);

        btnfuncionario.setText("FUNCIONARIO");
        btnfuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfuncionarioActionPerformed(evt);
            }
        });
        btnfuncionario.setBounds(225, 75, 160, 45);
        getContentPane().add(btnfuncionario);

        btncategoria.setText("CATEGORIA");
        btncategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncategoriaActionPerformed(evt);
            }
        });
        btncategoria.setBounds(35, 130, 160, 45);
        getContentPane().add(btncategoria);

        btnProduto.setText("PRODUTO");
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });
        btnProduto.setBounds(225, 130, 160, 45);
        getContentPane().add(btnProduto);

        btnpedido.setText("PEDIDO");
        btnpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpedidoActionPerformed(evt);
            }
        });
        btnpedido.setBounds(35, 185, 160, 45);
        getContentPane().add(btnpedido);

        btnitempedido.setText("ITEM PEDIDO");
        btnitempedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnitempedidoActionPerformed(evt);
            }
        });
        btnitempedido.setBounds(225, 185, 160, 45);
        getContentPane().add(btnitempedido);

        btnentregador.setText("ENTREGADOR");
        btnentregador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentregadorActionPerformed(evt);
            }
        });
        btnentregador.setBounds(35, 240, 160, 45);
        getContentPane().add(btnentregador);

        btnentrega.setText("ENTREGA");
        btnentrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentregaActionPerformed(evt);
            }
        });
        btnentrega.setBounds(225, 240, 160, 45);
        getContentPane().add(btnentrega);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("SUPLEMENTOS");
        jLabel1.setBounds(160, 27, 200, 39);
        getContentPane().add(jLabel1);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/abstrato-moderno-fundo-gradiente-ultravioleta_91606-73.jpg"))); // NOI18N
        jLabel3.setBounds(-30, -40, 500, 430);
        getContentPane().add(jLabel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclienteActionPerformed
frmcliente objfrmcliente=new frmcliente();
        objfrmcliente.setVisible(true);  
       
    }//GEN-LAST:event_btnclienteActionPerformed

    private void btnfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfuncionarioActionPerformed
     frmfuncionario objfrmfuncionario=new frmfuncionario();
        objfrmfuncionario.setVisible(true);  
       
    }//GEN-LAST:event_btnfuncionarioActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
      frmproduto objfrmproduto=new frmproduto();
        objfrmproduto.setVisible(true);  
       
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btncategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncategoriaActionPerformed
       frmcategoria objfrmcategoria=new frmcategoria();
        objfrmcategoria.setVisible(true);  
       
    }//GEN-LAST:event_btncategoriaActionPerformed

    private void btnpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpedidoActionPerformed
      frmpedido objfrmpedido=new frmpedido();
        objfrmpedido.setVisible(true);  
    }//GEN-LAST:event_btnpedidoActionPerformed

    private void btnitempedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnitempedidoActionPerformed
        frmitempedido objfrmitempedido = new frmitempedido();
        objfrmitempedido.setVisible(true);
    }//GEN-LAST:event_btnitempedidoActionPerformed

    private void btnentregadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentregadorActionPerformed
        frmentregador objfrmentregador = new frmentregador();
        objfrmentregador.setVisible(true);
    }//GEN-LAST:event_btnentregadorActionPerformed

    private void btnentregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentregaActionPerformed
        frmentrega objfrmentrega = new frmentrega();
        objfrmentrega.setVisible(true);
    }//GEN-LAST:event_btnentregaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btncategoria;
    private javax.swing.JButton btncliente;
    private javax.swing.JButton btnentrega;
    private javax.swing.JButton btnentregador;
    private javax.swing.JButton btnfuncionario;
    private javax.swing.JButton btnitempedido;
    private javax.swing.JButton btnpedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}


